# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Project
version=2.0.0
group=com.wfphantom.datagear
java_version=25

# Common
minecraft_version=26.2
mod_name=Datagear
mod_id=datagear
license=MIT
description=*data grinding noises*
minecraft_version_range=[26.2, 26.3)
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1
# Optional
mod_authors=WFPhantom
credits=
issue_tracker=https://github.com/WFPhantom/datagear/issues
homepage=https://modrinth.com/mod/datagear
logo=assets/datagear/icon.png

# https://fabricmc.net/develop/
fabric_loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.2.0.7-beta
# https://projects.neoforged.net/neoforged/moddevgradle
mdg_version=2.0.141
# Optional
update_json_url=https://api.modrinth.com/updates/datagear/forge_updates.json?neoforge=only

# Fabric Dependencies
fabric_api_version=0.153.0+26.2
fabric_kotlin_version=1.13.12+kotlin.2.4.0

# Neo Dependencies
neo_kotlin_version=2.12.1-k2.4.0-3.1